# Generated by Django 5.0.6 on 2024-06-14 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('liked_by', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('liked_by', 'post')},
        ),
    ]
